### ISSUE TITLE
ACT1_INFOGRAFIAS

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/actividad-1-infografia-ang3-l32#2]
[Uploading Infografia act1 AngelesGonzalezMartinezFUNDAMENTOS DE INGENIRIA.pdf…]()
[Uploading Infografia act1 AngelesGonzalezMartinezFUNDAMENTOS DE INGENIRIA.pdf…]()

**Comment by ang3-l32** [comment]
[Uploading Infografia act1 AngelesGonzalezMartinezFUNDAMENTOS DE INGENIRIA.pdf…]()

**Comment by ang3-l32** [comment]
[Uploading Infografia act1 AngelesGonzalezMartinezFUNDAMENTOS DE INGENIRIA.pdf…]()

**Comment by ang3-l32** [comment]
[Infografia act1 AngelesGonzalezMartinezFUNDAMENTOS DE INGENIRIA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-ang3-l32/files/9466703/Infografia.act1.AngelesGonzalezMartinezFUNDAMENTOS.DE.INGENIRIA.pdf)

**Comment by Valentiin01** [comment]
Calificación 19.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
